 name: Build and Push GPU Docker Image
     on: [push, workflow_dispatch]
     jobs:
       build:
         runs-on: ubuntu-latest
         steps:
         - uses: actions/checkout@v3
         - name: Log in to Docker Hub
           uses: docker/login-action@v2
           with:
             username: ${{ secrets.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD }}
         - name: Build and Push GPU Docker Image
           uses: docker/build-push-action@v4
           with:
             context: .
             file: ./docker/Dockerfile.gpu
             push: true
             tags: ${{ secrets.DOCKER_USERNAME }}/dia-tts-serverless:gpu-latest
    
